[package]
name = "multisync"
version = "0.1.0"
edition = "2021"
authors = ["Oliver Kiessler <kiessler@inceedo.com>"]
description = "A small CLI tool to pull multiple git repositories sequentially."
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0"
yaml_serde = "0.10"
shellexpand = "3.1"

[profile.release]
opt-level = 3
lto = true
